version: '3.7'

services:
  nginx-proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - 8080:8080
    networks:
      - shared-network

  client:
      build:
        dockerfile: Dockerfile
        context: ./sito-verifiche-docenti
      volumes:
        - /app/node_modules 
        - ./sito-verifiche-docenti:/app
      #ports:
        #- 4200:4200
      networks:
      - shared-network
  api-server:
      build:
        dockerfile: Dockerfile
        context: ./flask
      volumes:
        - ./flask:/app
      ports:
        - 5000:5000
      networks:
      - shared-network
networks:
  shared-network: